name: fisheeg
channels:
  - conda-forge
  - defaults

dependencies:
  # --- Base system packages ---
  - python=3.14
  - pip

  # --- Scientific / data packages available in conda ---
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - h5py
  - matplotlib
  - pywavelets
  - pytest
  - pytest-cov