name: Zip Data Folders # Zips on specific pushes so the site has updated data.

on:
  push:
    paths:
      - 'tools/analysis/CI_csv'
      - 'tools/analysis/plots'
      - 'tools/analysis/weights_csv'
  pull_request:
    paths:
      - 'tools/analysis/CI_csv'
      - 'tools/analysis/plots'
      - 'tools/analysis/weights_csv'
  workflow_dispatch:
      

jobs:
  zip-folders:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@main

      # Install zip utility sudo
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      # Zip folders (contents only) into downloads/
      - name: Zip folders
        run: |
          FOLDERS=('tools/analysis/CI_csv' 'tools/analysis/weights_csv' 'tools/analysis/plots')

          mkdir -p downloads
          for folder in "${FOLDERS[@]}"; do
            folder_name=$(basename "$folder")
            zipname="downloads/${folder_name}.zip"
            echo "Zipping contents of $folder -> $zipname"

            # Zip only the contents, not the parent folders
            cd "$folder"
            zip -r "../../../$zipname" .

            # Return to base dir
            cd ../../..
          done

      # Commit and push ZIPs
      - name: Commit and push ZIP files
        env:
            GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/*.zip
          git commit -m "Auto-update ZIPs for analysis folders" || echo "No changes to commit"

          # Push using the GITHUB_TOKEN
          git push 

